// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nullam.Data;

#nullable disable

namespace Nullam.Migrations
{
    [DbContext(typeof(NullamDbContext))]
    [Migration("20230618152746_ParticipantChanges")]
    partial class ParticipantChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventCompany", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("EventCompany");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("e426f972-f70d-480e-9876-913dc03393e0"),
                            CompanyId = new Guid("69bc0ae3-667b-4e09-82e9-46fe44883fbf")
                        },
                        new
                        {
                            EventId = new Guid("aa57c261-7765-41d0-898f-1d6621fb26f2"),
                            CompanyId = new Guid("c9c4dfea-07ae-4794-9895-a40373427e3a")
                        },
                        new
                        {
                            EventId = new Guid("ab2d252f-6c74-421b-bfdd-f323b4912157"),
                            CompanyId = new Guid("69bc0ae3-667b-4e09-82e9-46fe44883fbf")
                        },
                        new
                        {
                            EventId = new Guid("5eff17f2-f1b4-45fa-a8f7-b435be71a302"),
                            CompanyId = new Guid("c9c4dfea-07ae-4794-9895-a40373427e3a")
                        },
                        new
                        {
                            EventId = new Guid("d979c31b-617f-4fea-ac66-11d2ba628faf"),
                            CompanyId = new Guid("69bc0ae3-667b-4e09-82e9-46fe44883fbf")
                        },
                        new
                        {
                            EventId = new Guid("d979c31b-617f-4fea-ac66-11d2ba628faf"),
                            CompanyId = new Guid("c9c4dfea-07ae-4794-9895-a40373427e3a")
                        });
                });

            modelBuilder.Entity("EventPerson", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("EventPerson");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("e426f972-f70d-480e-9876-913dc03393e0"),
                            PersonId = new Guid("885d8f89-f52d-43b7-b3a3-bed2b5da951c")
                        },
                        new
                        {
                            EventId = new Guid("e426f972-f70d-480e-9876-913dc03393e0"),
                            PersonId = new Guid("db46fbef-fd61-4027-93d0-a2b46af2c96d")
                        },
                        new
                        {
                            EventId = new Guid("aa57c261-7765-41d0-898f-1d6621fb26f2"),
                            PersonId = new Guid("db46fbef-fd61-4027-93d0-a2b46af2c96d")
                        },
                        new
                        {
                            EventId = new Guid("ab2d252f-6c74-421b-bfdd-f323b4912157"),
                            PersonId = new Guid("885d8f89-f52d-43b7-b3a3-bed2b5da951c")
                        },
                        new
                        {
                            EventId = new Guid("5eff17f2-f1b4-45fa-a8f7-b435be71a302"),
                            PersonId = new Guid("885d8f89-f52d-43b7-b3a3-bed2b5da951c")
                        },
                        new
                        {
                            EventId = new Guid("d979c31b-617f-4fea-ac66-11d2ba628faf"),
                            PersonId = new Guid("885d8f89-f52d-43b7-b3a3-bed2b5da951c")
                        },
                        new
                        {
                            EventId = new Guid("d979c31b-617f-4fea-ac66-11d2ba628faf"),
                            PersonId = new Guid("db46fbef-fd61-4027-93d0-a2b46af2c96d")
                        });
                });

            modelBuilder.Entity("Nullam.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParticipantAmount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodTypeId")
                        .HasColumnType("int");

                    b.Property<double?>("RegistrationCode")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodTypeId");

                    b.HasIndex("RegistrationCode")
                        .IsUnique();

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bc0ae3-667b-4e09-82e9-46fe44883fbf"),
                            CreatedDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Info = "Qui simul cum eo ex Peloponneso in Siciliam venerat",
                            Name = "BlueBerry OÜ",
                            ParticipantAmount = 5,
                            PaymentMethodTypeId = 1,
                            RegistrationCode = 70334221.0
                        },
                        new
                        {
                            Id = new Guid("c9c4dfea-07ae-4794-9895-a40373427e3a"),
                            CreatedDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Info = "Sed Dion, fretus non tam",
                            Name = "WhiteBerry AS",
                            ParticipantAmount = 15,
                            PaymentMethodTypeId = 2,
                            RegistrationCode = 12341234.0
                        });
                });

            modelBuilder.Entity("Nullam.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurrenceTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e426f972-f70d-480e-9876-913dc03393e0"),
                            Info = "Minus sudorem excutiebat",
                            Name = "Sed ut perspiciatis unde ",
                            OccurrenceTime = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Libro plura"
                        },
                        new
                        {
                            Id = new Guid("aa57c261-7765-41d0-898f-1d6621fb26f2"),
                            Info = "Vulgus autem offensa in eum militum",
                            Name = "Zacynthios adulescentes",
                            OccurrenceTime = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Hic autem"
                        },
                        new
                        {
                            Id = new Guid("ab2d252f-6c74-421b-bfdd-f323b4912157"),
                            Info = " Qui motus non minus sudorem excutiebat, quam si in spatio decurreret.",
                            Name = "Dionis uxorem",
                            OccurrenceTime = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Syracusanus, nobili genere natus"
                        },
                        new
                        {
                            Id = new Guid("5eff17f2-f1b4-45fa-a8f7-b435be71a302"),
                            Info = "Itaque cum eum in custodiam dedisset et praefectus custodum quaesisset, quemadmodum servari vellet",
                            Name = "Perdiccam opprimendum",
                            OccurrenceTime = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Nam invidia ducum"
                        },
                        new
                        {
                            Id = new Guid("d979c31b-617f-4fea-ac66-11d2ba628faf"),
                            Info = "Alexandrum Magnum reges sunt appellati, ex hoc facillime potest iudicari, quod nemo Eumene vivo rex appellatus",
                            Name = "VII annos Philippo",
                            OccurrenceTime = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Alexandri liberis regnum servare"
                        });
                });

            modelBuilder.Entity("Nullam.Models.PaymentMethodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LabelText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LabelText = "Sularaha",
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            LabelText = "Pangaülekanne",
                            Name = "BankTransfer"
                        });
                });

            modelBuilder.Entity("Nullam.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IdCode")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethodTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCode")
                        .IsUnique();

                    b.HasIndex("PaymentMethodTypeId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("885d8f89-f52d-43b7-b3a3-bed2b5da951c"),
                            CreatedDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Malle",
                            IdCode = 49125238133L,
                            Info = "Qui simul cum eo ex Peloponneso in Siciliam venerat",
                            LastName = "Code",
                            PaymentMethodTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("db46fbef-fd61-4027-93d0-a2b46af2c96d"),
                            CreatedDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Martin",
                            IdCode = 39025325813L,
                            Info = "Sed Dion, fretus non tam",
                            LastName = "Crisp",
                            PaymentMethodTypeId = 2
                        });
                });

            modelBuilder.Entity("EventCompany", b =>
                {
                    b.HasOne("Nullam.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nullam.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventPerson", b =>
                {
                    b.HasOne("Nullam.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nullam.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nullam.Models.Company", b =>
                {
                    b.HasOne("Nullam.Models.PaymentMethodType", "PaymentMethodType")
                        .WithMany()
                        .HasForeignKey("PaymentMethodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethodType");
                });

            modelBuilder.Entity("Nullam.Models.Person", b =>
                {
                    b.HasOne("Nullam.Models.PaymentMethodType", "PaymentMethodType")
                        .WithMany()
                        .HasForeignKey("PaymentMethodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethodType");
                });
#pragma warning restore 612, 618
        }
    }
}
